### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by kunaldhariwal** [agiletechvn/tendermint-starterkit#1]
installation and all is done for tendermint.
Next i have to clone this repo, right?

What would be the next step then?

When and where do i run yarn start?
After abci-cli kvstore (Terminal 1)
tendermint node (terminal 2)
do i run this in terminal 3?

Please shed some light?

Thanks

**Comment by vjtc0n** [comment]
No need to install tendermint on your own machine.
We've already used docker-compose for installation.
You can run yarn at the root of the project.

Cheers,
